struct /*VFT*/ rvTools_vtbl
{
  void (__thiscall *dtr_rvTools)(rvTools *this);
  void *(__thiscall *GetInstance)(rvTools *this);
  void *(__thiscall *GetParentWindow)(rvTools *this);
  void *(__thiscall *GetDC)(rvTools *this);
  bool (__thiscall *IsParentWindowVisible)(rvTools *this);
  void (__thiscall *InitTool)(rvTools *this, const int, const idDict *);
  void (__thiscall *ShutdownTool)(rvTools *this, int);
  int (__thiscall *IsToolActive)(rvTools *this, int);
  void (__thiscall *Frame)(rvTools *this);
  void (__thiscall *Shutdown)(rvTools *this);
  void (__thiscall *HandleToolPrint)(rvTools *this, const char *);
  void (__thiscall *HandleMapChange)(rvTools *this);
  void (__thiscall *StartLevelLoad)(rvTools *this);
  void (__thiscall *EndLevelLoad)(rvTools *this);
  struct rvISourceControl *(__thiscall *GetSourceControl)(rvTools *this);
  bool (__thiscall *MakeGameCurrent)(rvTools *this);
  void (__thiscall *SetDefaultState)(rvTools *this);
  void (__thiscall *Set2D)(rvTools *this, int, int);
  void (__thiscall *DoRBFDialog)(rvTools *this, const char *);
  void (__thiscall *PlaybackEditorRefresh)(rvTools *this);
  void (__thiscall *ModViewShutdown)(rvTools *this, const char *);
  void (__thiscall *ModViewRun)(rvTools *this);
  int (__thiscall *ModViewGetJointStatus)(rvTools *this, int);
  bool (__thiscall *ModViewIsSurfaceSelected)(rvTools *this, const char *);
  bool (__thiscall *ModViewIsSurfaceHidden)(rvTools *this, const char *);
  const idVec4 *(__thiscall *ModViewGetBgrndColor)(rvTools *this);
  bool (__thiscall *FXEditorIsActive)(rvTools *this);
  void (__thiscall *FXEditorRefreshEffects)(rvTools *this);
  void (__thiscall *FXEditorPlayEffect)(rvTools *this, bool);
  void (__thiscall *FXEditorStopEffect)(rvTools *this);
  void (__thiscall *FXEditorRefreshMaterials)(rvTools *this);
  void (__thiscall *GEAllocateWindowWrapper)(rvTools *this, idWindow *);
  void (__thiscall *GEDeallocateWindowWrapper)(rvTools *this, idWindow *);
  void (__thiscall *GEFinish)(rvTools *this, idWindow *);
  void (__thiscall *GEAddScript)(rvTools *this, idWindow *, const char *, const char *);
  void (__thiscall *GEVariableDictSet)(rvTools *this, idWindow *, const char *, const char *);
  void (__thiscall *GESetStateKey)(rvTools *this, idWindow *, const char *, const char *, bool);
  void (*GEMessage)(rvTools *this, const char *, ...);
  void (__thiscall *DebuggerPrint)(rvTools *this, const char *);
  void (__thiscall *DebuggerCheckBreakpoint)(rvTools *this, idInterpreter *, idProgram *, int);
  void (__thiscall *DmapCleanupOptimizedShadowTris)(rvTools *this, int, srfTriangles_s *);
  bool (__thiscall *DmapSuperOptimizeOccluders)(rvTools *this, SOOData_s *, idVec4 *, int *, int, idPlane, idVec3);
  void (__thiscall *DmapOutputString)(rvTools *this, const char *);
  void (__thiscall *SetListenerArea)(rvTools *this, int);
  int (__thiscall *GetListenerArea)(rvTools *this);
  void (__thiscall *PhonemeGen)(rvTools *this, const idCmdArgs *);
  void (__thiscall *ShakesGen)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RoQFileEncode)(rvTools *this, const idCmdArgs *);
  void (__thiscall *Renderbump)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RenderbumpFlat)(rvTools *this, const idCmdArgs *);
  void (__thiscall *Dmap)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RunAAS)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RunAASDir)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RunReach)(rvTools *this, const idCmdArgs *);
  void (__thiscall *RunAASTactical)(rvTools *this, const idCmdArgs *);
  void (__thiscall *LocaliseGuis)(rvTools *this, const idCmdArgs *);
  void (__thiscall *LocaliseLipsyncs)(rvTools *this, const idCmdArgs *);
  void (__thiscall *LocaliseMaps)(rvTools *this, const idCmdArgs *);
  void (__thiscall *LocaliseValidateLipsyncs)(rvTools *this, const idCmdArgs *);
  void (__thiscall *LocaliseValidateStrings)(rvTools *this, const idCmdArgs *);
  bool (__thiscall *HandleMessage)(rvTools *this, tagMSG *);
  int (__thiscall *SetupPixelFormat)(rvTools *this, HDC__ *);
  bool (__thiscall *MakeCurrent)(rvTools *this, HDC__ *);
};