
#define glAccum glAccum
#define glAlphaFunc glAlphaFunc
#define glAreTexturesResident glAreTexturesResident
#define glArrayElement glArrayElement
#define glBegin glBegin
#define glBindTexture glBindTexture
#define glBitmap glBitmap
#define glBlendFunc glBlendFunc
#define glCallList glCallList
#define glCallLists glCallLists
#define glClear glClear
#define glClearAccum glClearAccum
#define glClearColor glClearColor
#define glClearDepth glClearDepth
#define glClearIndex glClearIndex
#define glClearStencil glClearStencil
#define glClipPlane glClipPlane
#define glColor3b glColor3b
#define glColor3bv glColor3bv
#define glColor3d glColor3d
#define glColor3dv glColor3dv
#define glColor3f glColor3f
#define glColor3fv glColor3fv
#define glColor3i glColor3i
#define glColor3iv glColor3iv
#define glColor3s glColor3s
#define glColor3sv glColor3sv
#define glColor3ub glColor3ub
#define glColor3ubv glColor3ubv
#define glColor3ui glColor3ui
#define glColor3uiv glColor3uiv
#define glColor3us glColor3us
#define glColor3usv glColor3usv
#define glColor4b glColor4b
#define glColor4bv glColor4bv
#define glColor4d glColor4d
#define glColor4dv glColor4dv
#define glColor4f glColor4f
#define glColor4fv glColor4fv
#define glColor4i glColor4i
#define glColor4iv glColor4iv
#define glColor4s glColor4s
#define glColor4sv glColor4sv
#define glColor4ub glColor4ub
#define glColor4ubv glColor4ubv
#define glColor4ui glColor4ui
#define glColor4uiv glColor4uiv
#define glColor4us glColor4us
#define glColor4usv glColor4usv
#define glColorMask glColorMask
#define glColorMaterial glColorMaterial
#define glColorPointer glColorPointer
#define glCopyPixels glCopyPixels
#define glCopyTexImage1D glCopyTexImage1D
#define glCopyTexImage2D glCopyTexImage2D
#define glCopyTexSubImage1D glCopyTexSubImage1D
#define glCopyTexSubImage2D glCopyTexSubImage2D
#define glCullFace glCullFace
#define glDeleteLists glDeleteLists
#define glDeleteTextures glDeleteTextures
#define glDepthFunc glDepthFunc
#define glDepthMask glDepthMask
#define glDepthRange glDepthRange
#define glDisable glDisable
#define glDisableClientState glDisableClientState
#define glDrawArrays glDrawArrays
#define glDrawBuffer glDrawBuffer
#define glDrawElements glDrawElements
#define glDrawPixels glDrawPixels
#define glEdgeFlag glEdgeFlag
#define glEdgeFlagPointer glEdgeFlagPointer
#define glEdgeFlagv glEdgeFlagv
#define glEnable glEnable
#define glEnableClientState glEnableClientState
#define glEnd glEnd
#define glEndList glEndList
#define glEvalCoord1d glEvalCoord1d
#define glEvalCoord1dv glEvalCoord1dv
#define glEvalCoord1f glEvalCoord1f
#define glEvalCoord1fv glEvalCoord1fv
#define glEvalCoord2d glEvalCoord2d
#define glEvalCoord2dv glEvalCoord2dv
#define glEvalCoord2f glEvalCoord2f
#define glEvalCoord2fv glEvalCoord2fv
#define glEvalMesh1 glEvalMesh1
#define glEvalMesh2 glEvalMesh2
#define glEvalPoint1 glEvalPoint1
#define glEvalPoint2 glEvalPoint2
#define glFeedbackBuffer glFeedbackBuffer
#define glFinish glFinish
#define glFlush glFlush
#define glFogf glFogf
#define glFogfv glFogfv
#define glFogi glFogi
#define glFogiv glFogiv
#define glFrontFace glFrontFace
#define glFrustum glFrustum
#define glGenLists glGenLists
#define glGenTextures glGenTextures
#define glGetBooleanv glGetBooleanv
#define glGetClipPlane glGetClipPlane
#define glGetDoublev glGetDoublev
#define glGetError glGetError
#define glGetFloatv glGetFloatv
#define glGetIntegerv glGetIntegerv
#define glGetLightfv glGetLightfv
#define glGetLightiv glGetLightiv
#define glGetMapdv glGetMapdv
#define glGetMapfv glGetMapfv
#define glGetMapiv glGetMapiv
#define glGetMaterialfv glGetMaterialfv
#define glGetMaterialiv glGetMaterialiv
#define glGetPixelMapfv glGetPixelMapfv
#define glGetPixelMapuiv glGetPixelMapuiv
#define glGetPixelMapusv glGetPixelMapusv
#define glGetPointerv glGetPointerv
#define glGetPolygonStipple glGetPolygonStipple
#define glGetString glGetString
#define glGetTexEnviv glGetTexEnviv
#define glGetTexEnvfv glGetTexEnvfv
#define glGetTexGendv glGetTexGendv
#define glGetTexGenfv glGetTexGenfv
#define glGetTexGeniv glGetTexGeniv
#define glGetTexImage glGetTexImage
#define glGetTexLevelParameterfv glGetTexLevelParameterfv
#define glGetTexLevelParameteriv glGetTexLevelParameteriv
#define glGetTexParameterfv glGetTexParameterfv
#define glGetTexParameteriv glGetTexParameteriv
#define glHint glHint
#define glIndexMask glIndexMask
#define glIndexPointer glIndexPointer
#define glIndexd glIndexd
#define glIndexdv glIndexdv
#define glIndexf glIndexf
#define glIndexfv glIndexfv
#define glIndexi glIndexi
#define glIndexiv glIndexiv
#define glIndexs glIndexs
#define glIndexsv glIndexsv
#define glIndexub glIndexub
#define glIndexubv glIndexubv
#define glInitNames glInitNames
#define glInterleavedArrays glInterleavedArrays
#define glIsEnabled glIsEnabled
#define glIsList glIsList
#define glIsTexture glIsTexture
#define glLightModelf glLightModelf
#define glLightModelfv glLightModelfv
#define glLightModeli glLightModeli
#define glLightModeliv glLightModeliv
#define glLightf glLightf
#define glLightfv glLightfv
#define glLighti glLighti
#define glLightiv glLightiv
#define glLineStipple glLineStipple
#define glLineWidth glLineWidth
#define glListBase glListBase
#define glLoadIdentity glLoadIdentity
#define glLoadMatrixd glLoadMatrixd
#define glLoadMatrixf glLoadMatrixf
#define glLoadName glLoadName
#define glLogicOp glLogicOp
#define glMap1d glMap1d
#define glMap1f glMap1f
#define glMap2d glMap2d
#define glMap2f glMap2f
#define glMapGrid1d glMapGrid1d
#define glMapGrid1f glMapGrid1f
#define glMapGrid2d glMapGrid2d
#define glMapGrid2f glMapGrid2f
#define glMaterialf glMaterialf
#define glMaterialfv glMaterialfv
#define glMateriali glMateriali
#define glMaterialiv glMaterialiv
#define glMatrixMode glMatrixMode
#define glMultMatrixd glMultMatrixd
#define glMultMatrixf glMultMatrixf
#define glNewList glNewList
#define glNormal3b glNormal3b
#define glNormal3bv glNormal3bv
#define glNormal3d glNormal3d
#define glNormal3dv glNormal3dv
#define glNormal3f glNormal3f
#define glNormal3fv glNormal3fv
#define glNormal3i glNormal3i
#define glNormal3iv glNormal3iv
#define glNormal3s glNormal3s
#define glNormal3sv glNormal3sv
#define glNormalPointer glNormalPointer
#define glOrtho glOrtho
#define glPassThrough glPassThrough
#define glPixelMapfv glPixelMapfv
#define glPixelMapuiv glPixelMapuiv
#define glPixelMapusv glPixelMapusv
#define glPixelStoref glPixelStoref
#define glPixelStorei glPixelStorei
#define glPixelTransferf glPixelTransferf
#define glPixelTransferi glPixelTransferi
#define glPixelZoom glPixelZoom
#define glPointSize glPointSize
#define glPolygonMode glPolygonMode
#define glPolygonOffset glPolygonOffset
#define glPolygonStipple glPolygonStipple
#define glPopAttrib glPopAttrib
#define glPopClientAttrib glPopClientAttrib
#define glPopMatrix glPopMatrix
#define glPopName glPopName
#define glPrioritizeTextures glPrioritizeTextures
#define glPushAttrib glPushAttrib
#define glPushClientAttrib glPushClientAttrib
#define glPushMatrix glPushMatrix
#define glPushName glPushName
#define glRasterPos2d glRasterPos2d
#define glRasterPos2dv glRasterPos2dv
#define glRasterPos2f glRasterPos2f
#define glRasterPos2fv glRasterPos2fv
#define glRasterPos2i glRasterPos2i
#define glRasterPos2iv glRasterPos2iv
#define glRasterPos2s glRasterPos2s
#define glRasterPos2sv glRasterPos2sv
#define glRasterPos3d glRasterPos3d
#define glRasterPos3dv glRasterPos3dv
#define glRasterPos3f glRasterPos3f
#define glRasterPos3fv glRasterPos3fv
#define glRasterPos3i glRasterPos3i
#define glRasterPos3iv glRasterPos3iv
#define glRasterPos3s glRasterPos3s
#define glRasterPos3sv glRasterPos3sv
#define glRasterPos4d glRasterPos4d
#define glRasterPos4dv glRasterPos4dv
#define glRasterPos4f glRasterPos4f
#define glRasterPos4fv glRasterPos4fv
#define glRasterPos4i glRasterPos4i
#define glRasterPos4iv glRasterPos4iv
#define glRasterPos4s glRasterPos4s
#define glRasterPos4sv glRasterPos4sv
#define glReadBuffer glReadBuffer
#define glReadPixels glReadPixels
#define glRectd glRectd
#define glRectdv glRectdv
#define glRectf glRectf
#define glRectfv glRectfv
#define glRecti glRecti
#define glRectiv glRectiv
#define glRects glRects
#define glRectsv glRectsv
#define glRenderMode glRenderMode
#define glRotated glRotated
#define glRotatef glRotatef
#define glScaled glScaled
#define glScalef glScalef
#define glScissor glScissor
#define glSelectBuffer glSelectBuffer
#define glShadeModel glShadeModel
#define glStencilFunc glStencilFunc
#define glStencilMask glStencilMask
#define glStencilOp glStencilOp
#define glTexCoord1d glTexCoord1d
#define glTexCoord1dv glTexCoord1dv
#define glTexCoord1f glTexCoord1f
#define glTexCoord1fv glTexCoord1fv
#define glTexCoord1i glTexCoord1i
#define glTexCoord1iv glTexCoord1iv
#define glTexCoord1s glTexCoord1s
#define glTexCoord1sv glTexCoord1sv
#define glTexCoord2d glTexCoord2d
#define glTexCoord2dv glTexCoord2dv
#define glTexCoord2f glTexCoord2f
#define glTexCoord2fv glTexCoord2fv
#define glTexCoord2i glTexCoord2i
#define glTexCoord2iv glTexCoord2iv
#define glTexCoord2s glTexCoord2s
#define glTexCoord2sv glTexCoord2sv
#define glTexCoord3d glTexCoord3d
#define glTexCoord3dv glTexCoord3dv
#define glTexCoord3f glTexCoord3f
#define glTexCoord3fv glTexCoord3fv
#define glTexCoord3i glTexCoord3i
#define glTexCoord3iv glTexCoord3iv
#define glTexCoord3s glTexCoord3s
#define glTexCoord3sv glTexCoord3sv
#define glTexCoord4d glTexCoord4d
#define glTexCoord4dv glTexCoord4dv
#define glTexCoord4f glTexCoord4f
#define glTexCoord4fv glTexCoord4fv
#define glTexCoord4i glTexCoord4i
#define glTexCoord4iv glTexCoord4iv
#define glTexCoord4s glTexCoord4s
#define glTexCoord4sv glTexCoord4sv
#define glTexCoordPointer glTexCoordPointer
#define	glTexEnvf glTexEnvf
#define	glTexEnvfv glTexEnvfv
#define	glTexEnvi glTexEnvi
#define	glTexEnviv glTexEnviv
#define glTexGend glTexGend
#define glTexGendv glTexGendv
#define glTexGenf glTexGenf
#define glTexGenfv glTexGenfv
#define glTexGeni glTexGeni
#define glTexGeniv glTexGeniv
#define glTexImage1D glTexImage1D
#define glTexImage2D glTexImage2D
#define glTexParameterf glTexParameterf
#define glTexParameterfv glTexParameterfv
#define glTexParameteri glTexParameteri
#define glTexParameteriv glTexParameteriv
#define glTexSubImage1D glTexSubImage1D
#define glTexSubImage2D glTexSubImage2D
#define glTranslated glTranslated
#define glTranslatef glTranslatef
#define glVertex2d glVertex2d
#define glVertex2dv glVertex2dv
#define glVertex2f glVertex2f
#define glVertex2fv glVertex2fv
#define glVertex2i glVertex2i
#define glVertex2iv glVertex2iv
#define glVertex2s glVertex2s
#define glVertex2sv glVertex2sv
#define glVertex3d glVertex3d
#define glVertex3dv glVertex3dv
#define glVertex3f glVertex3f
#define glVertex3fv glVertex3fv
#define glVertex3i glVertex3i
#define glVertex3iv glVertex3iv
#define glVertex3s glVertex3s
#define glVertex3sv glVertex3sv
#define glVertex4d glVertex4d
#define glVertex4dv glVertex4dv
#define glVertex4f glVertex4f
#define glVertex4fv glVertex4fv
#define glVertex4i glVertex4i
#define glVertex4iv glVertex4iv
#define glVertex4s glVertex4s
#define glVertex4sv glVertex4sv
#define glVertexPointer glVertexPointer
#define glViewport glViewport

#ifdef GLX_VERSION_1_1 // catch all for any GLX-aware situation
#define glXChooseVisual glXChooseVisual
#define glXCreateContext glXCreateContext
#define glXDestroyContext glXDestroyContext
#define glXMakeCurrent glXMakeCurrent
#define glXSwapBuffers glXSwapBuffers
#define glXGetProcAddressARB glXGetProcAddressARB
#endif
